//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpmonGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Sharpmons
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<int> defense { get; set; }
        public Nullable<int> dodge { get; set; }
        public Nullable<int> accuracy { get; set; }
        public Nullable<int> speed { get; set; }
    }
}
